import type { Metadata } from "next"
import { LegalLayout, type LegalContent } from "@/components/legal-layout"
import { JsonLdBreadcrumb } from "@/components/json-ld"

export const metadata: Metadata = {
  title: "Disclaimer - Compound Interest Calculator",
  description:
    "Financial disclaimer for Compound Interest Calculator — important limitations, no professional advice, and accuracy considerations for our free online tool.",
  alternates: { canonical: "https://top.net.im/disclaimer" },
  robots: { index: true, follow: true },
}

const enContent: LegalContent = {
  title: "Disclaimer",
  lastUpdated: "2026-07-30",
  intro:
    "Please read this disclaimer carefully before using the Compound Interest Calculator (the \"Service\"). By using the Service, you acknowledge and agree to the terms outlined below.",
  sections: [
    {
      heading: "Not Professional Financial Advice",
      body: "The Compound Interest Calculator is a mathematical tool that applies standard compound interest formulas based on user-provided inputs. IT DOES NOT PROVIDE FINANCIAL ADVICE, INVESTMENT ADVICE, TAX ADVICE, LEGAL ADVICE, OR ANY OTHER FORM OF PROFESSIONAL GUIDANCE. The results generated by this tool are purely mathematical computations and should not be interpreted as financial projections, investment recommendations, retirement planning advice, or any form of professional counsel.",
    },
    {
      heading: "Accuracy Limitations",
      body: "While we employ standard financial mathematics formulas, the calculations provided by this tool are simplified models that may not reflect real-world conditions. Actual investment returns are influenced by numerous factors not captured by our models, including but not limited to: market volatility and risk, management fees and expense ratios, changing interest rate environments, tax law changes, currency fluctuations, economic conditions, and individual investor circumstances. Results should be treated as rough estimates only.",
    },
    {
      heading: "No Investment Recommendations",
      body: "Nothing on this website constitutes an offer, solicitation, or recommendation to buy or sell any security, financial instrument, or investment product. Past performance and hypothetical projections do not guarantee future results. You should conduct your own research and due diligence before making any investment decisions.",
    },
    {
      heading: "No Guarantees",
      body: "WE MAKE NO GUARANTEES, REPRESENTATIONS, OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, ABOUT THE COMPLETENESS, ACCURACY, RELIABILITY, SUITABILITY, OR AVAILABILITY OF THE SERVICE OR THE INFORMATION, CALCULATIONS, OR RESULTS PROVIDED. Any reliance you place on such information is strictly at your own risk.",
    },
    {
      heading: "Tax and Inflation Assumptions",
      body: "The tax and inflation features in this tool use simplified assumptions: a flat capital gains tax rate applied uniformly to all gains, and a constant annual inflation rate applied to the nominal balance. Real-world tax systems are significantly more complex — they may involve progressive tax brackets, different rates for short-term vs. long-term capital gains, tax-advantaged account structures, deductions, and credits. Similarly, inflation rates vary over time and across different goods and services. The inflation-adjusted \"real value\" shown by this tool should be understood as an approximation only.",
    },
    {
      heading: "Compounding Frequency Note",
      body: "The Service allows you to select different compounding frequencies (annual, semiannual, quarterly, monthly, daily). In practice, the compounding frequency of real investment products may differ from what is displayed. Always verify the actual terms of any financial product with the issuing institution.",
    },
    {
      heading: "Use at Your Own Risk",
      body: "Your use of the Service and any actions you take based on its output are entirely at your own risk. We shall not be liable for any losses, damages, or adverse consequences — financial or otherwise — arising from your use of or reliance on the Service.",
    },
    {
      heading: "Consult a Professional",
      body: "We strongly recommend that you consult with a qualified financial advisor, certified financial planner (CFP), chartered financial analyst (CFA), tax professional, or other appropriate specialist before making any financial, investment, or retirement planning decisions. A qualified professional can consider your complete financial picture — including income, expenses, debts, risk tolerance, and long-term goals — in ways that a simple online calculator cannot.",
    },
    {
      heading: "External Links and Advertisements",
      body: "The Service may display advertisements and contain links to third-party websites, including financial services and products. We do not endorse, verify, or assume responsibility for any third-party content, products, or services. Any interactions with third-party advertisers or linked websites are solely between you and the third party.",
    },
    {
      heading: "Changes to This Disclaimer",
      body: "We may update this disclaimer at any time. Changes will be posted on this page with an updated date. Continued use of the Service after changes constitutes acceptance of the revised disclaimer.",
    },
  ],
}

const zhContent: LegalContent = {
  title: "免责声明",
  lastUpdated: "2026-07-30",
  intro:
    "在使用复利计算器（以下简称「服务」）之前，请仔细阅读本免责声明。使用本服务即表示你确认并同意下述条款。",
  sections: [
    {
      heading: "非专业财务建议",
      body: "复利计算器是一个基于用户输入数据应用标准复利公式的数学工具。它不提供财务建议、投资建议、税务建议、法律建议或任何其他形式的专业指导。本工具生成的结果纯属数学计算结果，不应理解为财务预测、投资推荐、退休规划建议或任何形式的专业意见。",
    },
    {
      heading: "准确性限制",
      body: "虽然我们使用标准金融数学公式，但本工具提供的计算是简化模型，可能无法反映真实世界的情况。实际投资回报受到众多本模型未考虑的因素影响，包括但不限于：市场波动与风险、管理费与费率比、变动的利率环境、税法变化、汇率波动、经济状况以及个人投资者情况。计算结果仅供参考，应视为粗略估计。",
    },
    {
      heading: "非投资建议",
      body: "本网站上的任何内容均不构成对买卖任何证券、金融工具或投资产品的要约、招揽或推荐。历史表现和假设性预测不能保证未来结果。在做出任何投资决策之前，你应自行进行研究和尽职调查。",
    },
    {
      heading: "无保证",
      body: "我们对服务的完整性、准确性、可靠性、适用性或可用性，以及所提供的信息、计算或结果，不作任何明示或暗示的保证、陈述或担保。你对此类信息的任何依赖均完全由你自行承担风险。",
    },
    {
      heading: "税务和通胀假设",
      body: "本工具中的税务和通胀功能使用简化假设：对所有收益统一适用固定资本利得税率，以及对名义余额适用固定年通胀率。现实世界的税务体系要复杂得多——可能涉及累进税率、短期与长期资本利得的差别税率、税收优惠账户结构、扣除和抵免等。同样，通胀率会随时间变化，不同商品和服务之间的通胀也不同。本工具显示的通胀调整后的「实际价值」应仅理解为近似值。",
    },
    {
      heading: "复利频率说明",
      body: "本服务允许你选择不同的复利频率（每年、每半年、每季度、每月、每日）。在实际中，真实投资产品的复利频率可能与显示的不同。请务必与发行机构核实任何金融产品的实际条款。",
    },
    {
      heading: "风险自负",
      body: "你使用本服务以及基于其输出采取的任何行动，均完全由你自行承担风险。对于因你使用或依赖本服务而产生的任何损失、损害或不良后果——无论是财务还是其他方面——我们概不负责。",
    },
    {
      heading: "咨询专业人士",
      body: "我们强烈建议你在做出任何财务、投资或退休规划决策之前，咨询合格的财务顾问、注册理财规划师 (CFP)、特许金融分析师 (CFA)、税务专业人士或其他合适的专家。合格的专业人士能够全面考虑你的财务状况——包括收入、支出、债务、风险承受能力和长期目标——这是一款简单的在线计算器无法做到的。",
    },
    {
      heading: "外部链接和广告",
      body: "本服务可能展示广告，并包含指向第三方网站（包括金融服务和产品）的链接。我们不对任何第三方内容、产品或服务表示认可、验证或承担任何责任。你与第三方广告商或链接网站的任何互动仅发生在你与该第三方之间。",
    },
    {
      heading: "免责声明变更",
      body: "我们可能随时更新本免责声明。变更将在本页面发布并注明更新日期。你在变更后继续使用本服务即表示你接受修订后的免责声明。",
    },
  ],
}

export default function DisclaimerPage() {
  return (
    <>
      <JsonLdBreadcrumb items={[
        { name: "Home", url: "https://top.net.im/" },
        { name: "Disclaimer", url: "https://top.net.im/disclaimer" },
      ]} />
      <LegalLayout en={enContent} zh={zhContent} />
    </>
  )
}
