import type { Metadata } from "next"
import { LegalLayout, type LegalContent } from "@/components/legal-layout"
import { JsonLdBreadcrumb } from "@/components/json-ld"

export const metadata: Metadata = {
  title: "Disclaimer - Compound Interest Calculator",
  description:
    "Financial disclaimer for Compound Interest Calculator — important limitations, no professional advice, and accuracy considerations for our free online tool.",
  alternates: { canonical: "https://top.net.im/disclaimer" },
  robots: { index: true, follow: true },
}

const content: LegalContent = {
  title: "Disclaimer",
  lastUpdated: "2026-07-30",
  intro:
    "Please read this disclaimer carefully before using the Compound Interest Calculator (the \"Service\"). By using the Service, you acknowledge and agree to the terms outlined below.",
  sections: [
    {
      heading: "Not Professional Financial Advice",
      body: "The Compound Interest Calculator is a mathematical tool that applies standard compound interest formulas based on user-provided inputs. IT DOES NOT PROVIDE FINANCIAL ADVICE, INVESTMENT ADVICE, TAX ADVICE, LEGAL ADVICE, OR ANY OTHER FORM OF PROFESSIONAL GUIDANCE. The results generated by this tool are purely mathematical computations and should not be interpreted as financial projections, investment recommendations, retirement planning advice, or any form of professional counsel.",
    },
    {
      heading: "Accuracy Limitations",
      body: "While we employ standard financial mathematics formulas, the calculations provided by this tool are simplified models that may not reflect real-world conditions. Actual investment returns are influenced by numerous factors not captured by our models, including but not limited to: market volatility and risk, management fees and expense ratios, changing interest rate environments, tax law changes, currency fluctuations, economic conditions, and individual investor circumstances. Results should be treated as rough estimates only.",
    },
    {
      heading: "No Investment Recommendations",
      body: "Nothing on this website constitutes an offer, solicitation, or recommendation to buy or sell any security, financial instrument, or investment product. Past performance and hypothetical projections do not guarantee future results. You should conduct your own research and due diligence before making any investment decisions.",
    },
    {
      heading: "No Guarantees",
      body: "WE MAKE NO GUARANTEES, REPRESENTATIONS, OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, ABOUT THE COMPLETENESS, ACCURACY, RELIABILITY, SUITABILITY, OR AVAILABILITY OF THE SERVICE OR THE INFORMATION, CALCULATIONS, OR RESULTS PROVIDED. Any reliance you place on such information is strictly at your own risk.",
    },
    {
      heading: "Tax and Inflation Assumptions",
      body: "The tax and inflation features in this tool use simplified assumptions: a flat capital gains tax rate applied uniformly to all gains, and a constant annual inflation rate applied to the nominal balance. Real-world tax systems are significantly more complex — they may involve progressive tax brackets, different rates for short-term vs. long-term capital gains, tax-advantaged account structures, deductions, and credits. Similarly, inflation rates vary over time and across different goods and services. The inflation-adjusted \"real value\" shown by this tool should be understood as an approximation only.",
    },
    {
      heading: "Compounding Frequency Note",
      body: "The Service allows you to select different compounding frequencies (annual, semiannual, quarterly, monthly, daily). In practice, the compounding frequency of real investment products may differ from what is displayed. Always verify the actual terms of any financial product with the issuing institution.",
    },
    {
      heading: "Use at Your Own Risk",
      body: "Your use of the Service and any actions you take based on its output are entirely at your own risk. We shall not be liable for any losses, damages, or adverse consequences — financial or otherwise — arising from your use of or reliance on the Service.",
    },
    {
      heading: "Consult a Professional",
      body: "We strongly recommend that you consult with a qualified financial advisor, certified financial planner (CFP), chartered financial analyst (CFA), tax professional, or other appropriate specialist before making any financial, investment, or retirement planning decisions. A qualified professional can consider your complete financial picture — including income, expenses, debts, risk tolerance, and long-term goals — in ways that a simple online calculator cannot.",
    },
    {
      heading: "External Links and Advertisements",
      body: "The Service may display advertisements and contain links to third-party websites, including financial services and products. We do not endorse, verify, or assume responsibility for any third-party content, products, or services. Any interactions with third-party advertisers or linked websites are solely between you and the third party.",
    },
    {
      heading: "Changes to This Disclaimer",
      body: "We may update this disclaimer at any time. Changes will be posted on this page with an updated date. Continued use of the Service after changes constitutes acceptance of the revised disclaimer.",
    },
  ],
}

export default function DisclaimerPage() {
  return (
    <>
      <JsonLdBreadcrumb items={[
        { name: "Home", url: "https://top.net.im/" },
        { name: "Disclaimer", url: "https://top.net.im/disclaimer" },
      ]} />
      <LegalLayout content={content} />
    </>
  )
}
